version: 0.2

environment_variables:
 plaintext:
   DJANGO_SETTINGS_MODULE: config.settings.test

phases:
 install:
   commands:
     - pip install -r requirements.txt
 pre_build:
   commands:
     - echo Prebuild ops
     - python --version
     - pylint $CODEBUILD_SRC_DIR/*.py
     - pylint --disable=E0611,E0401,C0103 $CODEBUILD_SRC_DIR/pharmacyproject/*.py
     - pylint --disable=E0307,W0611,C0114,C0103,C0411,C0325,C0114,R0914,W1309 $CODEBUILD_SRC_DIR/app/*.py
     

 build:
   commands:
     - echo "Building the application"
 post_build:
   commands:
     - echo Build completed on `date`

artifacts:
 files:
   - '**/*'