version: 0.2

environment_variables:
 plaintext:
   DJANGO_SETTINGS_MODULE: config.settings.test

phases:
 install:
   commands:
     - pip install -r requirements.txt
 pre_build:
   commands:
     - echo Prebuild ops
     - python --version
     
     

 build:
   commands:
     - echo "Building the application"
 post_build:
   commands:
     - echo Build completed on `date`

artifacts:
 files:
   - '**/*'